export const DUMMY_CURRENCIES = [
  // Major Currencies
  { value: "USD", label: "USD - United States Dollar" },
  { value: "EUR", label: "EUR - Euro" },
  { value: "GBP", label: "GBP - British Pound Sterling" },
  { value: "JPY", label: "JPY - Japanese Yen" },
  { value: "CHF", label: "CHF - Swiss Franc" },
  { value: "CAD", label: "CAD - Canadian Dollar" },
  { value: "AUD", label: "AUD - Australian Dollar" },
  { value: "NZD", label: "NZD - New Zealand Dollar" },

  // Asian Currencies
  { value: "CNY", label: "CNY - Chinese Yuan" },
  { value: "HKD", label: "HKD - Hong Kong Dollar" },
  { value: "SGD", label: "SGD - Singapore Dollar" },
  { value: "KRW", label: "KRW - South Korean Won" },
  { value: "TWD", label: "TWD - Taiwan Dollar" },
  { value: "THB", label: "THB - Thai Baht" },
  { value: "MYR", label: "MYR - Malaysian Ringgit" },
  { value: "IDR", label: "IDR - Indonesian Rupiah" },
  { value: "PHP", label: "PHP - Philippine Peso" },
  { value: "VND", label: "VND - Vietnamese Dong" },
  { value: "INR", label: "INR - Indian Rupee" },
  { value: "PKR", label: "PKR - Pakistani Rupee" },
  { value: "BDT", label: "BDT - Bangladeshi Taka" },
  { value: "LKR", label: "LKR - Sri Lankan Rupee" },
  { value: "NPR", label: "NPR - Nepalese Rupee" },

  // European Currencies
  { value: "SEK", label: "SEK - Swedish Krona" },
  { value: "NOK", label: "NOK - Norwegian Krone" },
  { value: "DKK", label: "DKK - Danish Krone" },
  { value: "PLN", label: "PLN - Polish Zloty" },
  { value: "CZK", label: "CZK - Czech Koruna" },
  { value: "HUF", label: "HUF - Hungarian Forint" },
  { value: "RON", label: "RON - Romanian Leu" },
  { value: "BGN", label: "BGN - Bulgarian Lev" },
  { value: "HRK", label: "HRK - Croatian Kuna" },
  { value: "RSD", label: "RSD - Serbian Dinar" },
  { value: "UAH", label: "UAH - Ukrainian Hryvnia" },
  { value: "RUB", label: "RUB - Russian Ruble" },
  { value: "BYN", label: "BYN - Belarusian Ruble" },
  { value: "MDL", label: "MDL - Moldovan Leu" },
  { value: "GEL", label: "GEL - Georgian Lari" },
  { value: "AMD", label: "AMD - Armenian Dram" },
  { value: "AZN", label: "AZN - Azerbaijani Manat" },
  { value: "KZT", label: "KZT - Kazakhstani Tenge" },
  { value: "KGS", label: "KGS - Kyrgyzstani Som" },
  { value: "TJS", label: "TJS - Tajikistani Somoni" },
  { value: "UZS", label: "UZS - Uzbekistani Som" },
  { value: "TMT", label: "TMT - Turkmenistani Manat" },

  // Middle Eastern & African Currencies
  { value: "AED", label: "AED - UAE Dirham" },
  { value: "SAR", label: "SAR - Saudi Riyal" },
  { value: "QAR", label: "QAR - Qatari Riyal" },
  { value: "KWD", label: "KWD - Kuwaiti Dinar" },
  { value: "BHD", label: "BHD - Bahraini Dinar" },
  { value: "OMR", label: "OMR - Omani Rial" },
  { value: "JOD", label: "JOD - Jordanian Dinar" },
  { value: "LBP", label: "LBP - Lebanese Pound" },
  { value: "ILS", label: "ILS - Israeli Shekel" },
  { value: "EGP", label: "EGP - Egyptian Pound" },
  { value: "MAD", label: "MAD - Moroccan Dirham" },
  { value: "TND", label: "TND - Tunisian Dinar" },
  { value: "DZD", label: "DZD - Algerian Dinar" },
  { value: "LYD", label: "LYD - Libyan Dinar" },
  { value: "ETB", label: "ETB - Ethiopian Birr" },
  { value: "KES", label: "KES - Kenyan Shilling" },
  { value: "UGX", label: "UGX - Ugandan Shilling" },
  { value: "TZS", label: "TZS - Tanzanian Shilling" },
  { value: "ZAR", label: "ZAR - South African Rand" },
  { value: "NGN", label: "NGN - Nigerian Naira" },
  { value: "GHS", label: "GHS - Ghanaian Cedi" },
  { value: "XOF", label: "XOF - West African CFA Franc" },
  { value: "XAF", label: "XAF - Central African CFA Franc" },

  // American Currencies
  { value: "MXN", label: "MXN - Mexican Peso" },
  { value: "BRL", label: "BRL - Brazilian Real" },
  { value: "ARS", label: "ARS - Argentine Peso" },
  { value: "CLP", label: "CLP - Chilean Peso" },
  { value: "COP", label: "COP - Colombian Peso" },
  { value: "PEN", label: "PEN - Peruvian Sol" },
  { value: "UYU", label: "UYU - Uruguayan Peso" },
  { value: "VES", label: "VES - Venezuelan Bolívar" },
  { value: "BOB", label: "BOB - Bolivian Boliviano" },
  { value: "PYG", label: "PYG - Paraguayan Guarani" },
  { value: "GTQ", label: "GTQ - Guatemalan Quetzal" },
  { value: "HNL", label: "HNL - Honduran Lempira" },
  { value: "NIO", label: "NIO - Nicaraguan Córdoba" },
  { value: "CRC", label: "CRC - Costa Rican Colón" },
  { value: "PAB", label: "PAB - Panamanian Balboa" },
  { value: "DOP", label: "DOP - Dominican Peso" },
  { value: "JMD", label: "JMD - Jamaican Dollar" },
  { value: "TTD", label: "TTD - Trinidad and Tobago Dollar" },
  { value: "BBD", label: "BBD - Barbadian Dollar" },
  { value: "XCD", label: "XCD - East Caribbean Dollar" },

  // Other Major Currencies
  { value: "TRY", label: "TRY - Turkish Lira" },

  // Additional Currencies
  { value: "ISK", label: "ISK - Icelandic Krona" },
  { value: "MKD", label: "MKD - Macedonian Denar" },
  { value: "ALL", label: "ALL - Albanian Lek" },
  { value: "BAM", label: "BAM - Bosnia and Herzegovina Mark" },
  { value: "MNT", label: "MNT - Mongolian Tugrik" },
  { value: "LAK", label: "LAK - Lao Kip" },
  { value: "KHR", label: "KHR - Cambodian Riel" },
  { value: "MMK", label: "MMK - Myanmar Kyat" },
  { value: "BND", label: "BND - Brunei Dollar" },
  { value: "FJD", label: "FJD - Fijian Dollar" },
  { value: "PGK", label: "PGK - Papua New Guinea Kina" },
  { value: "SBD", label: "SBD - Solomon Islands Dollar" },
  { value: "TOP", label: "TOP - Tongan Pa'anga" },
  { value: "VUV", label: "VUV - Vanuatu Vatu" },
  { value: "WST", label: "WST - Samoan Tala" },
  { value: "XPF", label: "XPF - CFP Franc" },
  { value: "AWG", label: "AWG - Aruban Florin" },
  { value: "BMD", label: "BMD - Bermudian Dollar" },
  { value: "KYD", label: "KYD - Cayman Islands Dollar" },
  { value: "BZD", label: "BZD - Belize Dollar" },
  { value: "GYD", label: "GYD - Guyanese Dollar" },
  { value: "SRD", label: "SRD - Surinamese Dollar" },
  { value: "BWP", label: "BWP - Botswanan Pula" },
  { value: "SZL", label: "SZL - Swazi Lilangeni" },
  { value: "LSL", label: "LSL - Lesotho Loti" },
  { value: "NAD", label: "NAD - Namibian Dollar" },
  { value: "MWK", label: "MWK - Malawian Kwacha" },
  { value: "ZMW", label: "ZMW - Zambian Kwacha" },
  { value: "BIF", label: "BIF - Burundian Franc" },
  { value: "DJF", label: "DJF - Djiboutian Franc" },
  { value: "KMF", label: "KMF - Comorian Franc" },
  { value: "RWF", label: "RWF - Rwandan Franc" },
  { value: "SCR", label: "SCR - Seychellois Rupee" },
  { value: "SOS", label: "SOS - Somali Shilling" },
  { value: "AOA", label: "AOA - Angolan Kwanza" },
  { value: "CDF", label: "CDF - Congolese Franc" },
  { value: "GMD", label: "GMD - Gambian Dalasi" },
  { value: "GNF", label: "GNF - Guinean Franc" },
  { value: "LRD", label: "LRD - Liberian Dollar" },
  { value: "MRO", label: "MRO - Mauritanian Ouguiya" },
  { value: "SLL", label: "SLL - Sierra Leonean Leone" },
  { value: "STD", label: "STD - São Tomé and Príncipe Dobra" },
];

export const FEATURED_CURRENCIES = [
  { value: "USD", label: "USD - United States Dollar" },
  { value: "EUR", label: "EUR - Euro" },
  { value: "JPY", label: "JPY - Japanese Yen" },
  { value: "GBP", label: "GBP - British Pound" },
  { value: "AUD", label: "AUD - Australian Dollar" },
  { value: "CAD", label: "CAD - Canadian Dollar" },
  { value: "CHF", label: "CHF - Swiss Franc" },
];

export const DEFAULT_VALUES = {
  amount: 0,
  fromCurrency: "",
  toCurrency: "",
  transactionDate: new Date().toLocaleDateString("en-US"),
  bankFee: 2,
};
